CREATE TABLE GASOLINERAS(
    ID_GASOLINERA int NOT NULL PRIMARY KEY IDENTITY(1, 1),
    CP int,
    DIRECCION VARCHAR(150),
    HORARIO VARCHAR(100),
    LATITUD FLOAT,
    LOCALIDAD VARCHAR(150),
    LONGITUD FLOAT,
    MARGEN VARCHAR(5),
    MUNICIPIO VARCHAR(100),
    ID_MUNICIPIO INT,
    ID_PROVINCIA INT,
    PROVINCIA VARCHAR(30),
    ROTULO VARCHAR(100),
    TIPO_VENTA VARCHAR(5),


);
    ALTER TABLE GASOLINERAS
    ADD CONSTRAINT UNIQUE_GASOLINERA UNIQUE(LATITUD, LONGITUD);

CREATE TABLE DATA_GASOLINERAS(
    ID_DATA int PRIMARY KEY NOT NULL IDENTITY(1, 1),
    ID_GASOLINERA int NOT NULL FOREIGN KEY REFERENCES GASOLINERAS(ID_GASOLINERA),
    FECHA datetime,
    PRECIO_BIODIESEL FLOAT,
    PRECIO_BIOETANOL FLOAT,
    PRECIO_GAS_NATURAL_COMPRIMIDO FLOAT,
    PRECIO_GAS_NATURAL_LICUADO FLOAT,
    PRECIO_GASES_LICUADOS_DEL_PETROLEO FLOAT,
    PRECIO_GASOLEO_A FLOAT,
    PRECIO_GASOLEO_B FLOAT,
    PRECIO_GASOLEO_PREMIUM FLOAT,
    PRECIO_GASOLINA_95_E10 FLOAT,
    PRECIO_GASOLINA_95_E5 FLOAT,
    PRECIO_GASOLINA_95_E5_PREMIUM FLOAT,    
    PRECIO_GASOLINA_98_E10 FLOAT,
    PRECIO_GASOLINA_98_E5 FLOAT,
    PRECIO_HIDROGENO FLOAT,
    REMISION VARCHAR(10),
    PORCENTAJE_BIOETANOL FLOAT,
    PORCENTAJE_ESTER_METILICO FLOAT,
    IDEESS INT,
    IDCCAA VARCHAR(10)
)
